package MetaData

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *TransactionAnalysis) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "TxsNum":
			z.TxsNum, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TxsNum")
				return
			}
		case "PreTxsNum":
			z.PreTxsNum, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "PreTxsNum")
				return
			}
		case "TxsList":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "TxsList")
				return
			}
			if cap(z.TxsList) >= int(zb0002) {
				z.TxsList = (z.TxsList)[:zb0002]
			} else {
				z.TxsList = make([]uint64, zb0002)
			}
			for za0001 := range z.TxsList {
				z.TxsList[za0001], err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "TxsList", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TransactionAnalysis) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "TxsNum"
	err = en.Append(0x83, 0xa6, 0x54, 0x78, 0x73, 0x4e, 0x75, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.TxsNum)
	if err != nil {
		err = msgp.WrapError(err, "TxsNum")
		return
	}
	// write "PreTxsNum"
	err = en.Append(0xa9, 0x50, 0x72, 0x65, 0x54, 0x78, 0x73, 0x4e, 0x75, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.PreTxsNum)
	if err != nil {
		err = msgp.WrapError(err, "PreTxsNum")
		return
	}
	// write "TxsList"
	err = en.Append(0xa7, 0x54, 0x78, 0x73, 0x4c, 0x69, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.TxsList)))
	if err != nil {
		err = msgp.WrapError(err, "TxsList")
		return
	}
	for za0001 := range z.TxsList {
		err = en.WriteUint64(z.TxsList[za0001])
		if err != nil {
			err = msgp.WrapError(err, "TxsList", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TransactionAnalysis) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "TxsNum"
	o = append(o, 0x83, 0xa6, 0x54, 0x78, 0x73, 0x4e, 0x75, 0x6d)
	o = msgp.AppendUint64(o, z.TxsNum)
	// string "PreTxsNum"
	o = append(o, 0xa9, 0x50, 0x72, 0x65, 0x54, 0x78, 0x73, 0x4e, 0x75, 0x6d)
	o = msgp.AppendUint64(o, z.PreTxsNum)
	// string "TxsList"
	o = append(o, 0xa7, 0x54, 0x78, 0x73, 0x4c, 0x69, 0x73, 0x74)
	o = msgp.AppendArrayHeader(o, uint32(len(z.TxsList)))
	for za0001 := range z.TxsList {
		o = msgp.AppendUint64(o, z.TxsList[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TransactionAnalysis) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "TxsNum":
			z.TxsNum, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TxsNum")
				return
			}
		case "PreTxsNum":
			z.PreTxsNum, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PreTxsNum")
				return
			}
		case "TxsList":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TxsList")
				return
			}
			if cap(z.TxsList) >= int(zb0002) {
				z.TxsList = (z.TxsList)[:zb0002]
			} else {
				z.TxsList = make([]uint64, zb0002)
			}
			for za0001 := range z.TxsList {
				z.TxsList[za0001], bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "TxsList", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TransactionAnalysis) Msgsize() (s int) {
	s = 1 + 7 + msgp.Uint64Size + 10 + msgp.Uint64Size + 8 + msgp.ArrayHeaderSize + (len(z.TxsList) * (msgp.Uint64Size))
	return
}
