package Message

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *RespondTCMCertMsg) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "workernumber":
			z.WorkerNumber, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "WorkerNumber")
				return
			}
		case "attestation":
			z.Attestation, err = dc.ReadBytes(z.Attestation)
			if err != nil {
				err = msgp.WrapError(err, "Attestation")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RespondTCMCertMsg) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "workernumber"
	err = en.Append(0x82, 0xac, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.WorkerNumber)
	if err != nil {
		err = msgp.WrapError(err, "WorkerNumber")
		return
	}
	// write "attestation"
	err = en.Append(0xab, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Attestation)
	if err != nil {
		err = msgp.WrapError(err, "Attestation")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RespondTCMCertMsg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "workernumber"
	o = append(o, 0x82, 0xac, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	o = msgp.AppendUint32(o, z.WorkerNumber)
	// string "attestation"
	o = append(o, 0xab, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendBytes(o, z.Attestation)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RespondTCMCertMsg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "workernumber":
			z.WorkerNumber, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WorkerNumber")
				return
			}
		case "attestation":
			z.Attestation, bts, err = msgp.ReadBytesBytes(bts, z.Attestation)
			if err != nil {
				err = msgp.WrapError(err, "Attestation")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RespondTCMCertMsg) Msgsize() (s int) {
	s = 1 + 13 + msgp.Uint32Size + 12 + msgp.BytesPrefixSize + len(z.Attestation)
	return
}
